const state={lang:localStorage.getItem('wte-lang')||'fr',theme:localStorage.getItem('wte-theme')||'dark',filter:localStorage.getItem('wte-filter')||'all',query:''};
const langs=['fr','en','ru','de','es','zh'];
const langMeta={fr:['FR','Français','Prochain événement'],en:['EN','English','Next event'],ru:['RU','Русский','Следующее событие'],de:['DE','Deutsch','Nächstes Event'],es:['ES','Español','Próximo evento'],zh:['ZH','中文','下一个活动']};
const months={fr:['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sep','Oct','Nov','Déc'],en:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],ru:['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'],de:['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'],es:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],zh:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']};
const raw=[
['winter','major','01-09','01-29',['Opération Hiver','Winter Operation','Зимняя операция','Winteroperation','Operación Invierno','冬季行动'],'Neige, missions en chaîne et récompenses progressives.','Véhicule premium hivernal, camouflage neige, 2 décals; caisse: véhicule 2–5 %, camo 18 %, décal 30 %.','Jouez les tâches quotidiennes tôt; les coupons vendables apparaissent après activation, avec délai de marché.'],
['valentine','minor','02-12','02-16',['Saint-Valentin','Valentine’s Day','День святого Валентина','Valentinstag','San Valentín','情人节活动'],'Une opération courte centrée sur les assistances et les victoires en escouade.','Décal cœur, titre et camouflage romantique; caisse: camo 25 %, décal 40 %, véhicule 1 %.','Groupez-vous pour finir les objectifs; vérifiez la négociabilité avant d’activer un coupon.'],
['craft','major','03-13','03-30',['Mars Craft-mania','March Craft-mania','Мартовская крафт-мания','März-Craft-Mania','Craft-manía de marzo','三月制造狂欢'],'Fabriquez des composants en bataille puis échangez-les contre une récompense de collection.','Véhicule premium de rang moyen, camouflages et décals; caisse: véhicule 3 %, camo 22 %, pièces 55 %.','Le farm en arcade accélère les composants; certaines étapes sont time-gated et les objets finaux sont échangeables.'],
['april','major','04-01','04-07',['Poisson d’avril','April Fools','День смеха','Aprilscherz','Día de los Inocentes','愚人节'],'Un mode expérimental décalé avec objectifs secrets et défis quotidiens.','Véhicule gag premium, décal surprise, titre; caisse: véhicule 2 %, décal 35 %, titre 45 %.','Lisez les objectifs cachés; les récompenses de mode peuvent devenir des coupons négociables.'],
['easter','minor','04-03','04-13',['Opération Pâques','Easter Operation','Пасхальная операция','Osteroperation','Operación Pascua','复活节行动'],'Chasse aux œufs et tâches de victoire pendant la période pascale.','Camouflage printanier, décor lapin, booster et chance de véhicule; caisse: camo 30 %, décal 35 %, véhicule 1 %.','Les tâches se cumulent en plusieurs batailles; économisez les boosters pour les objectifs de score.'],
['wood','major','05-08','05-24',['Woodened Steel','Woodened Steel','Woodened Steel','Woodened Steel','Woodened Steel','木钢行动'],'Construisez une machine en bois et acier à partir de ressources gagnées en jeu.','Véhicule événement premium, camo bois, décor et coupon; caisse: véhicule 4 %, camo 20 %, décor 32 %.','Surveillez les limites quotidiennes; les ressources sont échangeables au Market selon la phase de l’événement.'],
['nation','minor','05-22','05-26',['Anniversaire des nations','Nation Anniversary','Годовщина наций','Nationalfeiertag','Aniversario nacional','国家周年庆'],'Bonus thématiques et petites tâches dédiées aux arbres nationaux.','Décals historiques, titre et réduction de véhicule; caisse: décal 45 %, camo 20 %, coupon 2 %.','Changez de nation entre les manches; les coupons d’anniversaire sont souvent échangeables.'],
['dogs','minor','06-05','06-09',['Military Working Dogs','Military Working Dogs','Военные служебные собаки','Militärische Diensthunde','Perros de trabajo militar','军犬行动'],'Un hommage aux unités cynophiles avec objectifs de capture et de soutien.','Décal chien, icône de profil et camouflage; caisse: décal 48 %, camo 22 %, véhicule 1 %.','Les captures rapides rapportent davantage; pas de fabrication, récompenses accessibles sans time-gate.'],
['summer','major','06-19','07-19',['Bataille d’été','Summer Battle Pass','Летний боевой пропуск','Sommer-Battle-Pass','Pase de batalla de verano','夏季战斗通行证'],'Saison de Battle Pass avec niveaux gratuits et premium à débloquer.','Véhicules premium, décor, camouflages et coupons; caisse: véhicule 5 %, camo 18 %, décal 30 %.','Progressez chaque jour pour les missions; les coupons premium deviennent échangeables après activation.'],
['tournament','minor','07-03','07-12',['Tournoi des escadrons','Squadron Tournament','Турнир эскадрилий','Staffelturnier','Torneo de escuadrones','中队锦标赛'],'Compétition à équipes avec classement, manches et récompenses de participation.','Décal tournoi, titre, boosters et chance de coupon; caisse: décal 40 %, booster 45 %, véhicule 1 %.','Inscrivez votre escadron tôt; les matchs sont time-gated et les prix dépendent du classement.'],
['airshow','major','07-24','08-09',['Air Show','Air Show','Авиашоу','Air Show','Festival Aéreo','空军展演'],'Célébration aérienne: victoires, atterrissages et objectifs de pilotage.','Avion premium, livrée de démonstration et décals; caisse: avion 3 %, camo 24 %, décal 35 %.','Les batailles aériennes réalistes donnent plus de progression; gardez les coupons pour le Market.'],
['sale','minor','08-14','08-18',['Soldes pack d’été','Summer Pack Sale','Летняя распродажа наборов','Sommer-Paketverkauf','Rebajas de packs de verano','夏季礼包促销'],'Fenêtre de réductions sur les packs et bonus d’achat en boutique.','Coupons de véhicules premium, boosters et décorations; caisse: véhicule 2 %, booster 50 %, déco 25 %.','Comparez le prix en Golden Eagles et en pack; aucun farm requis, offre limitée dans le temps.'],
['tank','minor','09-04','09-10',['Journée des blindés','Armour Day','День бронетанковых войск','Tag der Panzertruppen','Día del blindaje','装甲部队日'],'Défis de blindage, éliminations et réparations avec récompenses rapides.','Camouflage urbain, décal technique et booster; caisse: camo 28 %, décal 40 %, véhicule 1 %.','Les chars moyens facilitent les objectifs; les tâches quotidiennes se réinitialisent à heure fixe.'],
['halloween','major','10-23','11-05',['Opération Halloween','Halloween Operation','Операция Хэллоуин','Halloween-Operation','Operación Halloween','万圣节行动'],'Événement nocturne à objectifs multiples, avec décorations sinistres et véhicules rares.','Véhicule premium spécial, camo nocturne, décor et décals; caisse: véhicule 4 %, camo 20 %, décal 28 %.','Planifiez les étapes avant la fin; les coupons rares sont échangeables mais soumis à un délai.'],
['black','major','11-20','11-30',['Black Friday','Black Friday','Чёрная пятница','Black Friday','Black Friday','黑色星期五'],'Promotions de fin d’année, tâches d’achat et récompenses de connexion.','Réductions, véhicules premium et camouflages exclusifs; caisse: véhicule 3 %, camo 22 %, booster 42 %.','Vérifiez les limites de stock et le Market; les offres disparaissent à la date de fin.'],
['anniversary','minor','12-04','12-08',['Anniversaire de War Thunder','War Thunder Anniversary','Годовщина War Thunder','War-Thunder-Jubiläum','Aniversario de War Thunder','战争雷霆周年庆'],'Bonus de connexion et missions anniversaires pour toute la communauté.','Décal anniversaire, titre, booster et chance de véhicule; caisse: décal 50 %, booster 35 %, véhicule 1 %.','Connectez-vous chaque jour; le meilleur rendement vient des victoires rapides et des assists.'],
['winterfest','major','12-11','12-29',['Opération Nouvel An','New Year Operation','Новогодняя операция','Neujahrsoperation','Operación de Año Nuevo','新年行动'],'Grande chasse hivernale de fin d’année avec récompenses en plusieurs paliers.','Véhicule premium, camouflages festifs, décals et décorations; caisse: véhicule 5 %, camo 20 %, décal 30 %.','Conservez les ressources pour le dernier palier; plusieurs coupons sont négociables après une période d’attente.'],
['tournament2','minor','12-18','12-22',['Coupe des vétérans','Veterans Cup','Кубок ветеранов','Veteranen-Cup','Copa de veteranos','老兵杯'],'Tournoi communautaire de clôture avec missions de spectateur et de participation.','Titre, décal commémoratif et boosters; caisse: décal 45 %, booster 40 %, véhicule 1 %.','Suivez le calendrier des matchs; récompenses de classement distribuées après validation des résultats.'],
['newyear','major','12-27','12-31',['Fête du Nouvel An','New Year Festival','Новогодний фестиваль','Neujahrsfest','Festival de Año Nuevo','新年庆典'],'Finale festive avec feux d’artifice, cadeaux quotidiens et dernière chaîne de tâches.','Véhicule premium festif, camo lumineux et décals; caisse: véhicule 4 %, camo 25 %, décal 35 %.','Terminez les tâches avant minuit UTC; les cadeaux non ouverts expirent avec l’événement.']
];
const copy={fr:{desc:'Une série de missions et de défis détaillés accompagne cet événement, avec progression par victoires, objectifs et activités thématiques.',coupons:'Les caisses contiennent des véhicules premium, camouflages, décals et objets de personnalisation; les taux indiqués sont des estimations.',info:'Optimisez vos tâches quotidiennes, vérifiez la négociabilité au Market et surveillez les étapes limitées dans le temps.'},en:{desc:'A chain of missions and detailed challenges accompanies this event, with progress through victories, objectives and themed activities.',coupons:'Crates contain premium vehicles, camouflage, decals and customization items; the listed rates are estimates.',info:'Optimize daily tasks, check Market tradability and watch for time-limited stages.'},ru:{desc:'Серия заданий и подробных испытаний сопровождает событие: прогресс зависит от побед, целей и тематических активностей.',coupons:'В ящиках могут быть премиумная техника, камуфляжи, декали и предметы оформления; указаны примерные шансы.',info:'Выполняйте ежедневные задачи, проверяйте возможность продажи на бирже и следите за ограниченными этапами.'},de:{desc:'Eine Reihe ausführlicher Aufgaben und Herausforderungen begleitet das Event; Fortschritt entsteht durch Siege und thematische Ziele.',coupons:'Kisten enthalten Premiumfahrzeuge, Tarnungen, Decals und Dekorationen; die angegebenen Quoten sind Schätzungen.',info:'Erledige Tagesaufgaben, prüfe die Handelbarkeit im Market und beachte zeitlich begrenzte Stufen.'},es:{desc:'Una cadena de misiones y desafíos detallados acompaña el evento, con progreso mediante victorias y objetivos temáticos.',coupons:'Las cajas contienen vehículos premium, camuflajes, calcomanías y personalización; las tasas son estimadas.',info:'Optimiza las tareas diarias, comprueba si se puede comerciar en el Market y vigila las fases limitadas.'},zh:{desc:'活动包含连续任务与详细挑战，通过胜利、目标和主题玩法逐步推进。',coupons:'箱子可能包含高级载具、涂装、贴花和装饰品；所列概率为估算值。',info:'优先完成每日任务，确认物品能否在市场交易，并留意限时阶段。'}};
function pack(row){const [id,type,start,end,names,d,c,i]=row;return {id,type,start,end,i18n:Object.fromEntries(langs.map((l,k)=>{const base=copy[l];return [l,{name:names[k],desc:l==='fr'?d:`${names[k]} — ${base.desc}`,coupons:l==='fr'?c:`${names[k]}: ${base.coupons}`,info:l==='fr'?i:`${names[k]}: ${base.info}`}] }))};}
const events=raw.map(pack);
function L(e,field){return e.i18n[state.lang]?.[field]||e.i18n.en?.[field]||e.i18n.fr[field]}
const getEventName=e=>L(e,'name'),getEventDesc=e=>L(e,'desc'),getCoupons=e=>L(e,'coupons'),getInfo=e=>L(e,'info');
const $=s=>document.querySelector(s); const dateOf=e=>new Date(`2026-${e.start}T00:00:00`); const endOf=e=>new Date(`2026-${e.end}T23:59:59`);
function formatDate(e){return `${e.start.split('-').reverse().join('/')} — ${e.end.split('-').reverse().join('/')}`}
function renderCards(){const q=state.query.toLowerCase(); const list=events.filter(e=>(state.filter==='all'||e.type===state.filter)&&(!q||[getEventName(e),getEventDesc(e),getCoupons(e)].join(' ').toLowerCase().includes(q))); $('#cards').innerHTML=list.map((e,n)=>`<article class="event-card ${e.type}" id="event-${e.id}" style="--i:${n}"><div class="card-head"><span class="tag">${e.type==='major'?'MAJOR':'MINOR'}</span><time>${formatDate(e)}</time></div><h3>${getEventName(e)}</h3><p>${getEventDesc(e)}</p><div class="detail"><strong>▣ ${state.lang==='fr'?'Caisses':state.lang==='en'?'Crates':state.lang==='ru'?'Ящики':state.lang==='de'?'Kisten':state.lang==='es'?'Cajas':'箱子'}</strong><p>${getCoupons(e)}</p></div><div class="detail"><strong>⌁ ${state.lang==='fr'?'Conseils':state.lang==='en'?'Field notes':state.lang==='ru'?'Советы':state.lang==='de'?'Tipps':state.lang==='es'?'Consejos':'建议'}</strong><p>${getInfo(e)}</p></div></article>`).join('')||'<p class="empty">No event found.</p>';}
function renderCalendar(){const year=2026; const weekdays=state.lang==='fr'?['L','M','M','J','V','S','D']:['M','T','W','T','F','S','S']; let h=''; for(let m=0;m<12;m++){const first=new Date(year,m,1), days=new Date(year,m+1,0).getDate(), offset=(first.getDay()+6)%7; h+=`<section class="month"><h3>${months[state.lang][m]} <small>2026</small></h3><div class="weekdays">${weekdays.map(x=>`<b>${x}</b>`).join('')}</div><div class="days">${'<i></i>'.repeat(offset)}${Array.from({length:days},(_,d)=>{const day=d+1;const es=events.filter(e=>{const a=dateOf(e),z=endOf(e),x=new Date(year,m,day);return x>=a&&x<=z});return `<button class="day ${es.length?'has-event':''}" ${es.length?`data-event="${es[0].id}"`:''}>${day}${es.length?'<em></em>':''}</button>`}).join('')}</div></section>`;} $('.calendar-grid').innerHTML=h; document.querySelectorAll('.day[data-event]').forEach(b=>b.onclick=()=>document.getElementById('event-'+b.dataset.event)?.scrollIntoView({behavior:'smooth',block:'center'}));}
function nextEvent(){const now=new Date();let e=events.map(e=>({e,t:dateOf(e)})).find(x=>x.t>now);const target=e?e.t:new Date('2027-01-09T00:00:00'); $('#next-name').textContent=e?getEventName(e.e):'2027 · Winter Operation';return target;}
function tick(){const t=nextEvent()-Date.now();const s=Math.max(0,Math.floor(t/1000));const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60;$('#countdown').innerHTML=[d,h,m,sec].map((x,i)=>`<span><b>${String(x).padStart(2,'0')}</b><small>${['DAYS','HOURS','MIN','SEC'][i]}</small></span>`).join('');}
function apply(){document.documentElement.dataset.theme=state.theme;$('#lang').value=state.lang;document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=langMeta[state.lang][n.dataset.i18n]);renderCards();renderCalendar();tick();localStorage.setItem('wte-lang',state.lang);localStorage.setItem('wte-theme',state.theme);localStorage.setItem('wte-filter',state.filter);}
document.addEventListener('DOMContentLoaded',()=>{ $('#lang').onchange=e=>{state.lang=e.target.value;apply()};$('#theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';apply()};$('#search').oninput=e=>{state.query=e.target.value;renderCards()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCards();apply()});apply();setInterval(tick,1000);});
